name: SamuelVargas
favicon: null
layout_spectrum: 0.92198
typography_spectrum: 0.40688
title: Samuel Vargas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#011e2e'
    - '#fdffff'
    - '#a1adb9'
    - '#707070'
    - '#305336'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
