name: SamuelVargas
favicon: null
layout_spectrum: 0.92198
typography_spectrum: 0.62836
title: Samuel Vargas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fbf9fa'
    - '#adadad'
    - '#696969'
    - '#72ffd5'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
